### ISSUE TITLE
state size does not change dynamically with custom board size

### ISSUE THREAD

**Issue by honglu2875** [CGLemon/pyDLGO#4]
https://github.com/CGLemon/pyDLGO/blob/c237ab644c8bd9f63a52c24e5a5595d1cab3d9c4/board.py#L89
This line seems to use the global constant for 19x19 board. But if the board is initialized for smaller sizes, there seems to be a redundancy in storing the states (a bunch of unnecessary "3"'s). Should it be changed?

**Comment by CGLemon** [comment]
Sorry about that. The current ```BOARD_SIZE``` is 9. The released model depend on it. Past 19 is a bug. I fixed it already.

The every go engines I know use the fixed array instead of dynamic array, like Leela Zero, Kata Go, Pachi... . Actually I have no ideal about it. I guess it is in order to bug-free. There are some methods may use the out of board area and make it store some special informations ( Not used in pyDLGO ). It may much complexity if we use dynamic one.

Addition, ```self.state``` is not only 9x9. It is (9+2)x(9x2). That because we apply the mailbox. [Here](https://www.chessprogramming.org/Mailbox) is the description.
